COHORTS = [
    {
        "id": "kl-sme-2026",
        "name": "Kuala Lumpur SME Growth Cohort 2026",
        "program": "EcoSync AI Accelerator",
        "location": "Kuala Lumpur",
        "focus_domains": ["food and beverage", "retail", "small business"],
        "status": "active",
    }
]

STARTUPS = [
    {
        "id": "startup-nasi-next",
        "name": "NasiNext Cloud Kitchen",
        "domain": "food and beverage",
        "location": "Kuala Lumpur",
        "stage": "growth",
        "pain_points": ["delivery margins", "kitchen operations", "brand awareness"],
        "goals": ["expand to 3 districts", "improve profitability", "launch catering"],
        "revenue_range": "RM50k-RM100k monthly",
        "team_size": 18,
        "market": "urban office workers and students",
        "requested_support": ["unit economics", "digital marketing", "operations"],
        "founder_notes": "Strong repeat orders but delivery costs and prep bottlenecks limit expansion.",
        "cohort_id": "kl-sme-2026",
    },
    {
        "id": "startup-halalbite",
        "name": "HalalBite Ready Meals",
        "domain": "food and beverage",
        "location": "Kuala Lumpur",
        "stage": "early revenue",
        "pain_points": ["halal certification", "retail distribution", "packaging"],
        "goals": ["enter supermarkets", "complete halal audit", "reduce spoilage"],
        "revenue_range": "RM15k-RM30k monthly",
        "team_size": 8,
        "market": "busy families and convenience stores",
        "requested_support": ["compliance", "supply chain", "retail partnerships"],
        "founder_notes": "Demand is promising, but certification and cold-chain planning are gaps.",
        "cohort_id": "kl-sme-2026",
    },
    {
        "id": "startup-batikdesk",
        "name": "BatikDesk Studio",
        "domain": "retail SME",
        "location": "Kuala Lumpur",
        "stage": "validation",
        "pain_points": ["online conversion", "inventory planning", "pricing"],
        "goals": ["improve ecommerce sales", "build corporate gifting channel"],
        "revenue_range": "RM8k-RM15k monthly",
        "team_size": 5,
        "market": "tourists, offices, and gift buyers",
        "requested_support": ["digital marketing", "pricing", "B2B sales"],
        "founder_notes": "Beautiful products but inconsistent lead flow and unclear B2B packaging.",
        "cohort_id": "kl-sme-2026",
    },
]

MENTORS = [
    {
        "id": "mentor-aisha",
        "name": "Aisha Rahman",
        "expertise": ["food operations", "unit economics", "delivery optimization"],
        "industries": ["food and beverage", "cloud kitchen", "SME"],
        "location": "Kuala Lumpur",
        "languages": ["English", "Malay"],
        "availability": "4 hours/month",
        "past_roles": ["Regional Operations Lead at food delivery platform"],
        "mentoring_style": "hands-on operator",
        "preferred_stage": ["early revenue", "growth"],
    },
    {
        "id": "mentor-daniel",
        "name": "Daniel Tan",
        "expertise": ["digital marketing", "brand growth", "ecommerce conversion"],
        "industries": ["food and beverage", "retail SME", "consumer goods"],
        "location": "Petaling Jaya",
        "languages": ["English", "Malay", "Mandarin"],
        "availability": "3 hours/month",
        "past_roles": ["Growth consultant for DTC brands"],
        "mentoring_style": "structured growth sprints",
        "preferred_stage": ["validation", "early revenue", "growth"],
    },
    {
        "id": "mentor-farid",
        "name": "Farid Iskandar",
        "expertise": ["halal compliance", "food safety", "supply chain"],
        "industries": ["food and beverage", "manufacturing", "SME"],
        "location": "Kuala Lumpur",
        "languages": ["Malay", "English"],
        "availability": "2 hours/month",
        "past_roles": ["Halal audit advisor", "F&B manufacturing manager"],
        "mentoring_style": "compliance checklist coaching",
        "preferred_stage": ["early revenue", "growth"],
    },
    {
        "id": "mentor-mei",
        "name": "Mei Lin Wong",
        "expertise": ["fundraising", "financial planning", "pricing"],
        "industries": ["SME", "consumer goods", "retail SME"],
        "location": "Kuala Lumpur",
        "languages": ["English", "Mandarin"],
        "availability": "5 hours/month",
        "past_roles": ["CFO coach for accelerator cohorts"],
        "mentoring_style": "financial model reviews",
        "preferred_stage": ["validation", "early revenue", "growth"],
    },
]
